# Site
name: 'Tahoma Times'
title: Tahoma Times
description: 'The Summit Tahoma Newspaper'
logo: 'assets/images/tahoma_times_logo.jpg'
favicon: 'favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'mmehra.ta@mysummitps.org'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: [ "_pages" ]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
  medha:
    name: Medha Mehra
    shortname: Medha
    #    site:
    avatar: assets/images/avatar_medha.jpg
    bio: "Hi! I'm Medha, a senior and the Head Editor of the Tahoma Times. I also lead the Journalism Club and designed our website. Happy reading + puzzling!"
    email: mmehra.ta@mysummitps.org
  #    twitter:

  george:
    name: George Harper
    shortname: George
    avatar: assets/images/avatar_george.png
    bio: "Howdy! I'm a 12th grade artist and writer at Summit Tahoma. This is my second (and sadly last) year in charge of the Folklore Corner, so I'm hoping to make it a good one. I hope it'll teach you something new, brighten your day, and leave a lasting impact."

  julia:
    name: Julia Somlo
    shortname: Julia
    avatar: assets/images/avatar_julia.jpg
    bio: "Hi I am a 10th grade Technology Journalist at Tahoma. I enjoy covering pieces on technology (AI), climate change (AI impact), and business news (AI)."

  daniil:
    name: Daniil Solovov
    shortname: Daniil
    avatar: assets/images/avatar_daniil.jpeg
    bio: "Hello, I am 12th grade Journalist at Tahoma. I wish to cover pieces on geopolitics,governments, and random conspiracy theories and political topics."

  juliab:
    name: Julia Burk
    shortname: Julia
    avatar: assets/images/avatar_juliab.jpg
    bio: "Hello! I'm Julia, a 9th grade writer for the Tahoma Times. I'll cover anything that interests me, usually current events going on in the world and my many opinions."

  scarlett:
    name: Scarlett Juszkiewicz
    shortname: Scarlett
    avatar: assets/images/avatar_scarlett.jpg
    bio: "Hello I'm Scarlett. I'm a 9th grade Writer at Tahoma Times. I usually enjoy writing about cryptids, marine biology, and really anything that interests me."

  maya:
    name: Maya Shasky
    shortname: Maya
    avatar: assets/images/avatar_maya.jpg
    bio: "Hi! My name is Maya and I'm a 10th grader here at Summit Tahoma. I like to write about a variety of things  but most things that I stay focused on are teens mental health and how mental health can be developed."

  ammanuel:
    name: Ammanuel Abiy
    shortname: Ammanuel
    avatar: assets/images/avatar_ammanuel.png
    bio: "Hi I’m a 12th grade marketer at Tahoma I help out with getting people hyped to read our articles."

  rehaan:
    name: Rehaan Mundy
    shortname: Rehaan
    avatar: assets/images/avatar_rehaan.jpeg
    bio: "Hello! My name is Rehaan Mundy: a 12th grader interested in writing about math, computer science, and economics."

  jeet:
    name: Jeet Lad
    shortname: Jeet
    avatar: assets/images/avatar_jeet.jpeg
    bio: "My name’s Jeet and I’m in marketing. I enjoy motorcycles!"

  claire:
    name: Claire Goshko
    shortname: Claire
    avatar: assets/images/avatar_claire.JPG
    bio: "Hello, I’m a junior and I do writing and marketing. I enjoy writing about student life and events going on."

  sada:
    name: Sada Bruhns
    shortname: Sada
    avatar: assets/images/avatar_sada.jpg
    bio: "Hi! I'm a 12th grade Journalist at Tahoma. I enjoy covering pieces on finance and local Tahoma news."

  maddie:
    name: Madeline Flowers
    shortname: Maddie
    avatar: assets/images/avatar_maddie.jpeg
    bio: "Hi I’m a junior journalist and photographer. I enjoy covering pieces on current events and summit life."

  luka:
    name: Luke Barnett
    shortname: Luka
    avatar: assets/images/avatar_luka.png
    bio: "Professional yapper and psychology enthusiast. Will gladly evaluate your brain. Hit me up"


  kaiden:
    name: Kaiden Hickson
    shortname: Kaiden
    avatar: assets/images/avatar_kaiden.jpg
    bio: "Hi! I am a journalist and photographer in 12th grade at Summit Tahoma. I cover topics about nature, non-national politics, and language & culture."

  #Not Updated Yet
  jette:
    name: Jette Sandstrom
    shortname: Jette
    avatar: assets/images/avatar_jette.jpg
    bio: "I am a 10th grade marketer at Tahoma Times. I will advertise this club and our articles."
    email: jsandstrom.ta@mysummitps.org

  millen:
    name: Millen Kidane
    shortname: Millen
    avatar: assets/images/avatar_millen.png
    bio: "Hi, my name is Millen Kidane. I am an 11th grade marketer at Tahoma. I will help spread the word about our stories."
    email: mkidane.ta@mysummitps.org

  sarah:
    name: Sarah Johnson
    shortname: Sarah
    avatar: assets/images/avatar_sarah.jpg
    bio: "Hi! I'm a junior and the head of marketing for the Tahoma Times. I will be advertising articles written by other students."
    email: sjohnson.ta@mysummitps.org

  sahana:
    name: Sahana Vimal
    shortname: Sahana
    avatar: assets/images/avatar_sahana.jpg
    bio: "Hi I'm a junior, lead photographer and I run our instagram page @tahoma_journalism (:"
    email: svimal.ta@mysummitps.org

  nolan:
    name: Nolan Ku
    shortname: Nolan
    avatar: assets/images/avatar_nolan.jpeg
    bio: "I’m a Junior and writer at Summit Tahoma. I love to cover topics in the tech space and covering the latest advancements in that field."

  rachel:
    name: Rachel Ignatovsky
    shortname: Rachel
    avatar: assets/images/avatar_rachel.jpg
    bio: "Hi! I am an 11th grader and I enjoy writing statistical essays and sharing my opinions on different types of topics such as video games, criminology, and celebrity news."

  miriam:
    name: Miriam Hunter
    shortname: Miriam
    avatar: assets/images/avatar_miriam.jpeg
    bio: "I am a beginner journalist and 11th grader at Tahoma. I enjoy discussing current politics, environmental causes, and school events."

  addy:
    name: Addy Carpenter
    shortname: Addy
    avatar: assets/images/avatar_addy.jpg
    bio: "HI!  I am an 11th grader, I like making recipes of pasta, politics, and Taylor Swift. "

  saarang:
    name: Saarang Sumesh
    shortname: Saarang
    avatar: assets/images/avatar_saarang.jpg
    bio: "I'm a junior working in Marketing, and I enjoy covering both global and local stories related to Tahoma."


  #Past Contributors
  sean:
    name: Sean Dolan
    shortname: Sean
    avatar: assets/images/avatar_sean.jpg
    bio: "[2023-2025 Contributor] I am Sean, and this is my second year covering news at the Tahoma Times. I enjoy covering stories surrounding this school or other important stuff in this world."
    email: sdolan.ta@mysummitps.org

  anush:
    name: Anush Narasimhan
    shortname: Anush
    avatar: assets/images/avatar_anush.jpg
    bio: "[2023-2025 Contributor] Hi! I'm Anush Narasimhan, a 12th grade Journalist at Tahoma. I am Kannadiga Tamilian and passionate about covering social issues, Tahoma news, South Asia, and political and social issues."
    email: anarasimhan.de@mysummitps.org

  timothy:
    name: Timothy Dao
    shortname: Timothy
    avatar: assets/images/avatar_timothy.png
    bio: "[2024-2025 Contributor] Hi, I'm Timothy, a guest editor for the Tahoma Times."
    email: tdao.ta@mysummitps.org

  kiyo:
    name: Kiyo Ishida
    shortname: Kiyo
    avatar: assets/images/avatar_kiyo.jpg
    bio: "[2024-2025 Contributor] Salutations! I'm a 9th grade writer and illustrator at Tahoma! I enjoy writing about upcoming events, hilarious but interesting questions or surveys and Tahoma news!"

  kayleigh:
    name: Kayleigh L. Vantrees
    shortname: Kayleigh
    avatar: assets/images/avatar_kayleigh.jpg
    bio: "[2023-2025 Contributor] Hello! I am an illustrator for the journalism club at Tahoma. I enjoy drawing topics about special school events, students, and humorous things. "
    email: kvantrees.ta@mysummitps.org

  georgios:
    name: Georgios Kakouros
    shortname: Georgios
    avatar: assets/images/avatar_georgios.jpg
    bio: "[2024-2025 Contributor] Hello, my name is Georgios Kakouros and I am the wielder of the camera! (Photographer). I enjoy taking photos of almost anything imaginable!"

  laney:
    name: Laney McBride
    shortname: Laney
    avatar: assets/images/avatar_laney.jpeg
    bio: "[2023-24 Contributor] Hi! I am Laney McBride, a 9th grade Journalist and Photographer at Tahoma. I enjoy covering pieces on climate change, politics, and local Tahoma news."
    email: lmcbride.ta@mysummitps.org

  meg:
    name: Meg Mulcaster
    shortname: Meg
    avatar: assets/images/avatar_meg.jpg
    bio: "[2023-24 Contributor] Hi! I'm a 10th grade Journalist (and sometimes photographer!) here at Tahoma. I cover local Tahoma news, editorials, and world news."
    email: mmulcaster.ta@mysummitps.org

  ashley:
    name: Ashley M. L.
    shortname: Ashley
    avatar: assets/images/avatar_ashley.jpg
    bio: "[2023-24 Contributor] Hi! I'm in 11th grade photographer and marketer at Tahoma. I enjoy covering pieces of school events, nature, fashion and food."
    email: amozoleon.ta@mysummitps.org

  mason:
    name: Mason Johnston
    shortname: Mason
    avatar: assets/images/avatar_mason.jpeg
    bio: "[2023-24 Contributor] I’m in 10th grade, and I love to illustrate. I want to bring life to the Tahoma news with little comics and drawings."
    email: wjohnston.de@mysummitps.org

  baja:
    name: Baja Allen
    shortname: Baja
    avatar: assets/images/avatar_baja.jpg
    bio: "[2023-24 Contributor] My name is Baja Allen and I am a journalist. I will be covering politics and write op eds about current political topics and issues facing us both nationally and locally. I will also write about movies or tv shows when there is one that is better than the rookie."
    email: ballen.ta@mysummitps.org


#  arya:
#    name: Arya Lurie
#    shortname: Arya
#    avatar: assets/images/avatar_arya.png
#    bio: "Hii! I'm a 9th grader on the marketing team at Tahoma. I help the marketing director."

#  alyson:
#    name: Alyson Ruiz
#    shortname: Alyson
#    avatar: assets/images/avatar_alyson.png
#    bio: "Hello I'm a 9th grade Journalist and Photographer. And I want to cover climate change "
#
#  jett:
#    name: Jett Da Rocha
#    shortname: Jett
#    avatar: assets/images/avatar_jett.png
#    bio: "Hi. I'm a 9th grade Journalist at Tahoma. I enjoy covering personal stories about other people and what their life was like."


  #  anna:
  #    name: Anna Fitzgerald
  #    shortname: Anna
  #    avatar: assets/images/avatar_anna.jpeg
  #    bio: "Hello! I’m a 10th grader Journalist and Illustrator at Tahoma. I enjoy drawing and writing small comic strips and local Tahoma news."
  #    email: afitzgerald.de@mysummitps.org

  #  autumn:
  #    name: Autumn Oliver
  #    shortname: Autumn
  #    avatar: assets/images/avatar_autumn.jpg
  #    bio: "Hi! I'm a 10th grade Journalist and Photographer at Tahoma. I enjoy covering pieces on climate change, politics, and local Tahoma news."
  #    email: aoliver.ta@mysummitps.org

  #  t:
  #    name: T Kim
  #    shortname: T
  #    avatar: assets/images/avatar_t.jpeg
  #    bio: "I’m interested in video journalism and taking pictures for events and helping the writers with they they need help with."
  #    email: tkim.ta@mysummitps.org

  #  addie:
  #    name: Addie Allen
  #    shortname: Addie
  #    avatar: assets/images/avatar_addie.jpg
  #    bio: "Hi! i'm Addie, a 10th grade journalist at Tahoma. I enjoy covering pieces on my interests."
  #    email: aallen.ta@mysummitps.org

  #  simon:
  #    name: Simon Lee
  #    shortname: Simon
  #    avatar: assets/images/avatar_simon.jpeg
  #    bio: "I'm a 10th grader illustartor at tahoma. I like to draw comics and write about sports."
  #    email: slee.de@mysummitps.org

  # takuma:
  #    name: Takuma Nakagawa
  #    shortname: Takuma
  #    avatar: assets/images/avatar_takuma.png
  #    bio: "Hello; I am a 10th grader at Tahoma, joining as an illustrator and a photographer! My main skill would be logo/title designing but I'm also interested in taking and collecting photos for other topics as well, especially nature and wildlife around the school."
  #    email: tnakagawa.de@mysummitps.org

#  alicia:
#    name: Alicia
#    shortname: Alicia
#    avatar: assets/images/avatar_ali.jpg
#    bio: "Hi! I'm a 10th grade Journalist at Tahoma. I enjoy interviews, writing, and researching about pieces."
#    email: aarnonileitedeabreu.ta@mysummitps.org
#
#  annabelle:
#    name: Annabelle Zubrod
#    shortname: Annabelle
#    avatar: assets/images/avatar_annabelle.webp
#    bio: "Hi i'm a 10th grade illustrator at Tahoma, I enjoy drawing."
#    email: azubrod.ta@mysummitps.org
#
#    magnus:
#      name: Magnus Oelsner
#      shortname: Magnus
#      avatar: assets/images/avatar_magnus.jpeg
#      bio: "Hi I’m Magnus"
#      email: moelsner.ta@mysummitps.org

  #  oskar:
  #    name: Oskar Brady
  #    shortname: Oskar
  #    avatar: assets/images/avatar_oskar.jpeg
  #    bio: "I take pictures and write words; mostly about culture and local events."
  #    email: obrady.ta@mysummitps.org



  #    sal:
  #      name:           Sal
  #      site:           https://www.wowthemes.net
  #      avatar:         /assets/images/avatar1.jpg
  #      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
  #      email:          wowthemesnet@gmail.com
  #      twitter:        https://twitter.com/wowthemesnet
  #
  #    jane:
  #      name:           Jane
  #      site:           https://www.wowthemes.net
  #      avatar:         /assets/images/avatar2.jpg
  #      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
  #      email:          fakemail@gmail.com
  #      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: medha
      avatar: assets/images/medha_text.png

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page


contributor_types:
  - author
  - editor
  - contributor
  - translator
  - reviewer
  - supervisor
  - manager
  - director
  - producer
  - executive_producer
  - illustrator
  - photographer
  - designer
  - developer
  - writer

# Syntax
markdown: GFM
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [ README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules ]